apiVersion: v2
name: forecast-parser
version: 1.0.0
description: A Helm chart for energinet-singularity/forecast-parser

dependencies:
  - name: file-mover
    version: 1.0.0
    repository: "https://energinet-singularity.github.io/helm-registry/"
