apiVersion: v2
name: forecast-parser
description: A Helm chart for energinet-singularity/forecast-parser
version: 1.1.5

dependencies:
  - name: file-mover
    repository: "https://energinet-singularity.github.io/helm-registry/"
    version: 1.1.2
